site_name: Blog{Code}
repo_name: fiddelis
repo_url: https://github.com/Fiddelis/code

theme:
  name: terminal
  palette: gruvbox_dark
  language: pt-BR
  features:
    - revision.date
    - navigation.side.indexes
plugins:
  - search

markdown_extensions:
  # Python Markdown  
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: "#"
      permalink_title: Anchor link to this section for reference

  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: 
        - docs